In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from sklearn.metrics import mean_absolute_error 
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import arff
test=arff.loadarff(r"C:\\Users\\Nexas\\Northeastern\FruitFlies_TEST.arff")
train=arff.loadarff(r"C:\\Users\\Nexas\\Northeastern\FruitFlies_TRAIN.arff")

In [2]:
from pandas import DataFrame

In [3]:
fftest = pd.DataFrame(test[0])

In [4]:
fftest.head()

att1      att2      att3      att4      att5      att6      att7  \
0  0.002502 -0.000671 -0.000977  0.002106 -0.001190  0.000427  0.000397   
1  0.003174  0.001373 -0.000702  0.000336  0.000153  0.001190 -0.001678   
2 -0.002686 -0.001404  0.000061  0.000793 -0.000366 -0.000488 -0.001160   
3  0.002869  0.001892  0.002441  0.003052  0.004395  0.003174  0.003601   
4  0.000916  0.000214  0.000336  0.000824 -0.000763 -0.000275 -0.001465   

       att8      att9     att10  ...   att4992   att4993   att4994   att4995  \
0 -0.001129  0.001862  0.000671  ... -0.004517 -0.002899 -0.002991 -0.001923   
1  0.000885  0.002655 -0.000488  ...  0.001923 -0.001831 -0.002441  0.002136   
2 -0.000580 -0.000549 -0.001007  ... -0.000854 -0.001923 -0.001099 -0.002258   
3  0.003876  0.001984  0.002472  ...  0.001923  0.003479  0.003357  0.003387   
4 -0.001312 -0.001373 -0.002167  ... -0.003143 -0.004639 -0.006927 -0.004913   

    att4996   att4997   att4998   att4999   att5000           target  
0 -0.003326 -0.004974 -0.006165 -0.005402 -0.005615  b'melanogaster'  
1  0.000397  0.000153  0.001526 -0.000488 -0.000854  b'melanogaster'  
2  0.000244 -0.003235 -0.004486 -0.000092 -0.000122  b'melanogaster'  
3  0.002869  0.003357  0.006287  0.003998  0.003693  b'melanogaster'  
4  0.003204  0.022491  0.035614  0.033569  0.033356  b'melanogaster'  

[5 rows x 5001 columns]

In [5]:
fftrain = pd.DataFrame(train[0])

In [6]:
fftrain.head()

att1      att2      att3      att4      att5      att6      att7  \
0  0.000244  0.001831 -0.000061 -0.001312  0.001587  0.000153  0.000214   
1 -0.000244  0.000275 -0.000153 -0.001251 -0.000458  0.000671  0.001465   
2  0.002350 -0.002441 -0.001373  0.000122 -0.000183  0.002563  0.000092   
3  0.001465  0.001221 -0.000305 -0.001129 -0.002411  0.001251  0.000336   
4  0.000397 -0.000061 -0.000641  0.000336 -0.000366 -0.000641 -0.000458   

       att8      att9     att10  ...   att4992   att4993   att4994   att4995  \
0  0.000885 -0.000641  0.000580  ... -0.000275  0.002563  0.003113  0.004272   
1  0.002441  0.001190 -0.000732  ... -0.003143 -0.004883 -0.006561 -0.005310   
2 -0.000061 -0.001312  0.000763  ...  0.000458 -0.003113 -0.003113 -0.001953   
3 -0.001648 -0.001923 -0.000549  ...  0.002869  0.000458 -0.001648  0.001892   
4 -0.000824 -0.001984  0.000305  ... -0.000793 -0.000183  0.001587  0.002594   

    att4996   att4997   att4998   att4999   att5000           target  
0  0.004364  0.004791  0.006165  0.003967  0.001251  b'melanogaster'  
1 -0.001862  0.002411  0.007233  0.013367  0.016144  b'melanogaster'  
2 -0.000641  0.001251  0.001648 -0.000824  0.001373  b'melanogaster'  
3 -0.002197  0.002258  0.003113  0.000000 -0.002319  b'melanogaster'  
4 -0.001099 -0.000671  0.000824  0.000793  0.003143  b'melanogaster'  

[5 rows x 5001 columns]

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
fftrain

att1      att2      att3      att4      att5      att6      att7  \
0      0.000244  0.001831 -0.000061 -0.001312  0.001587  0.000153  0.000214   
1     -0.000244  0.000275 -0.000153 -0.001251 -0.000458  0.000671  0.001465   
2      0.002350 -0.002441 -0.001373  0.000122 -0.000183  0.002563  0.000092   
3      0.001465  0.001221 -0.000305 -0.001129 -0.002411  0.001251  0.000336   
4      0.000397 -0.000061 -0.000641  0.000336 -0.000366 -0.000641 -0.000458   
...         ...       ...       ...       ...       ...       ...       ...   
17254  0.004883  0.004150  0.003754  0.004913  0.004486  0.004944  0.005310   
17255  0.001526  0.000977 -0.000488  0.000519  0.003021  0.001923  0.000549   
17256 -0.006012 -0.003967 -0.005096 -0.003265 -0.001251  0.000122  0.001312   
17257  0.000519 -0.000824  0.002045 -0.000061 -0.001709 -0.002838  0.002686   
17258  0.000122 -0.000031  0.001312  0.000244 -0.000427 -0.001862  0.001617   

           att8      att9     att10  ...   att4992   att4993   att4994  \
0      0.000885 -0.000641  0.000580  ... -0.000275  0.002563  0.003113   
1      0.002441  0.001190 -0.000732  ... -0.003143 -0.004883 -0.006561   
2     -0.000061 -0.001312  0.000763  ...  0.000458 -0.003113 -0.003113   
3     -0.001648 -0.001923 -0.000549  ...  0.002869  0.000458 -0.001648   
4     -0.000824 -0.001984  0.000305  ... -0.000793 -0.000183  0.001587   
...         ...       ...       ...  ...       ...       ...       ...   
17254  0.004791  0.007111  0.007080  ...  0.001709  0.006134  0.005646   
17255  0.000427  0.000641 -0.000336  ...  0.000977  0.000336  0.000916   
17256  0.003906  0.003479  0.001404  ... -0.004181 -0.003265  0.001526   
17257  0.000977 -0.000458  0.001129  ...  0.003845  0.003876  0.002533   
17258  0.000183 -0.000763  0.000153  ... -0.001556  0.000122  0.001740   

        att4995   att4996   att4997   att4998   att4999   att5000  \
0      0.004272  0.004364  0.004791  0.006165  0.003967  0.001251   
1     -0.005310 -0.001862  0.002411  0.007233  0.013367  0.016144   
2     -0.001953 -0.000641  0.001251  0.001648 -0.000824  0.001373   
3      0.001892 -0.002197  0.002258  0.003113  0.000000 -0.002319   
4      0.002594 -0.001099 -0.000671  0.000824  0.000793  0.003143   
...         ...       ...       ...       ...       ...       ...   
17254  0.006195  0.005768  0.003967  0.004089  0.001190  0.000153   
17255  0.006989  0.008728  0.009521  0.005249 -0.006744 -0.009827   
17256  0.005554  0.006165  0.007416  0.007477  0.008209  0.004883   
17257  0.002655  0.002869  0.000793  0.000916  0.001953  0.000824   
17258  0.002838  0.000061 -0.000305  0.000671  0.002014  0.001648   

                target  
0      b'melanogaster'  
1      b'melanogaster'  
2      b'melanogaster'  
3      b'melanogaster'  
4      b'melanogaster'  
...                ...  
17254     b'zaprionus'  
17255     b'zaprionus'  
17256     b'zaprionus'  
17257     b'zaprionus'  
17258     b'zaprionus'  

[17259 rows x 5001 columns]

In [9]:
fftrain.head()

att1      att2      att3      att4      att5      att6      att7  \
0  0.000244  0.001831 -0.000061 -0.001312  0.001587  0.000153  0.000214   
1 -0.000244  0.000275 -0.000153 -0.001251 -0.000458  0.000671  0.001465   
2  0.002350 -0.002441 -0.001373  0.000122 -0.000183  0.002563  0.000092   
3  0.001465  0.001221 -0.000305 -0.001129 -0.002411  0.001251  0.000336   
4  0.000397 -0.000061 -0.000641  0.000336 -0.000366 -0.000641 -0.000458   

       att8      att9     att10  ...   att4992   att4993   att4994   att4995  \
0  0.000885 -0.000641  0.000580  ... -0.000275  0.002563  0.003113  0.004272   
1  0.002441  0.001190 -0.000732  ... -0.003143 -0.004883 -0.006561 -0.005310   
2 -0.000061 -0.001312  0.000763  ...  0.000458 -0.003113 -0.003113 -0.001953   
3 -0.001648 -0.001923 -0.000549  ...  0.002869  0.000458 -0.001648  0.001892   
4 -0.000824 -0.001984  0.000305  ... -0.000793 -0.000183  0.001587  0.002594   

    att4996   att4997   att4998   att4999   att5000           target  
0  0.004364  0.004791  0.006165  0.003967  0.001251  b'melanogaster'  
1 -0.001862  0.002411  0.007233  0.013367  0.016144  b'melanogaster'  
2 -0.000641  0.001251  0.001648 -0.000824  0.001373  b'melanogaster'  
3 -0.002197  0.002258  0.003113  0.000000 -0.002319  b'melanogaster'  
4 -0.001099 -0.000671  0.000824  0.000793  0.003143  b'melanogaster'  

[5 rows x 5001 columns]

In [10]:
fftrain.target

0        b'melanogaster'
1        b'melanogaster'
2        b'melanogaster'
3        b'melanogaster'
4        b'melanogaster'
              ...       
17254       b'zaprionus'
17255       b'zaprionus'
17256       b'zaprionus'
17257       b'zaprionus'
17258       b'zaprionus'
Name: target, Length: 17259, dtype: object

In [11]:
y = fftrain.target

In [12]:
from sklearn import preprocessing

In [13]:
pp = preprocessing.LabelEncoder()


In [14]:
ye = pp.fit_transform(y)

In [15]:
ye

array([0, 0, 0, ..., 2, 2, 2])

In [16]:
fftrainx = fftrain.drop(['target'], axis=1)

In [17]:
fftrainx

att1      att2      att3      att4      att5      att6      att7  \
0      0.000244  0.001831 -0.000061 -0.001312  0.001587  0.000153  0.000214   
1     -0.000244  0.000275 -0.000153 -0.001251 -0.000458  0.000671  0.001465   
2      0.002350 -0.002441 -0.001373  0.000122 -0.000183  0.002563  0.000092   
3      0.001465  0.001221 -0.000305 -0.001129 -0.002411  0.001251  0.000336   
4      0.000397 -0.000061 -0.000641  0.000336 -0.000366 -0.000641 -0.000458   
...         ...       ...       ...       ...       ...       ...       ...   
17254  0.004883  0.004150  0.003754  0.004913  0.004486  0.004944  0.005310   
17255  0.001526  0.000977 -0.000488  0.000519  0.003021  0.001923  0.000549   
17256 -0.006012 -0.003967 -0.005096 -0.003265 -0.001251  0.000122  0.001312   
17257  0.000519 -0.000824  0.002045 -0.000061 -0.001709 -0.002838  0.002686   
17258  0.000122 -0.000031  0.001312  0.000244 -0.000427 -0.001862  0.001617   

           att8      att9     att10  ...   att4991   att4992   att4993  \
0      0.000885 -0.000641  0.000580  ...  0.000793 -0.000275  0.002563   
1      0.002441  0.001190 -0.000732  ... -0.001892 -0.003143 -0.004883   
2     -0.000061 -0.001312  0.000763  ... -0.001770  0.000458 -0.003113   
3     -0.001648 -0.001923 -0.000549  ...  0.002075  0.002869  0.000458   
4     -0.000824 -0.001984  0.000305  ... -0.002014 -0.000793 -0.000183   
...         ...       ...       ...  ...       ...       ...       ...   
17254  0.004791  0.007111  0.007080  ...  0.003479  0.001709  0.006134   
17255  0.000427  0.000641 -0.000336  ...  0.001648  0.000977  0.000336   
17256  0.003906  0.003479  0.001404  ... -0.003418 -0.004181 -0.003265   
17257  0.000977 -0.000458  0.001129  ...  0.001617  0.003845  0.003876   
17258  0.000183 -0.000763  0.000153  ... -0.000793 -0.001556  0.000122   

        att4994   att4995   att4996   att4997   att4998   att4999   att5000  
0      0.003113  0.004272  0.004364  0.004791  0.006165  0.003967  0.001251  
1     -0.006561 -0.005310 -0.001862  0.002411  0.007233  0.013367  0.016144  
2     -0.003113 -0.001953 -0.000641  0.001251  0.001648 -0.000824  0.001373  
3     -0.001648  0.001892 -0.002197  0.002258  0.003113  0.000000 -0.002319  
4      0.001587  0.002594 -0.001099 -0.000671  0.000824  0.000793  0.003143  
...         ...       ...       ...       ...       ...       ...       ...  
17254  0.005646  0.006195  0.005768  0.003967  0.004089  0.001190  0.000153  
17255  0.000916  0.006989  0.008728  0.009521  0.005249 -0.006744 -0.009827  
17256  0.001526  0.005554  0.006165  0.007416  0.007477  0.008209  0.004883  
17257  0.002533  0.002655  0.002869  0.000793  0.000916  0.001953  0.000824  
17258  0.001740  0.002838  0.000061 -0.000305  0.000671  0.002014  0.001648  

[17259 rows x 5000 columns]

In [18]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(fftrainx, ye, test_size=0.2)

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rfc5 =RandomForestClassifier(n_estimators=5)

In [236]:
rfc50 =RandomForestClassifier(n_estimators=50)

In [237]:
rfc500 =RandomForestClassifier(n_estimators=500)

In [21]:
rfc5.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=5)

In [359]:
rfc50.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=50)

In [360]:
rfc500.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=500)

In [361]:
ypred5 = rfc5.predict(xtest)

In [362]:
ypred50 = rfc50.predict(xtest)

In [363]:
ypred500 = rfc500.predict(xtest)

In [377]:
ypred5[1:50]

array([1, 1, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 0, 2, 2, 2, 0, 2, 2, 1, 1,
       0, 2, 1, 2, 2, 2, 2, 1, 0, 2, 1, 2, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       2, 2, 1, 2, 1])

In [378]:
ypred50[1:50]

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 0, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 1, 1, 2, 1, 2,
       2, 2, 1, 2, 2])

In [379]:
ypred500[1:50]

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 0, 1, 0, 2, 2, 1, 1, 2, 1, 2,
       2, 2, 1, 2, 2])

In [339]:
from sklearn import metrics

In [367]:
acc5 = metrics.accuracy_score(ytest,ypred5)

In [368]:
acc50 = metrics.accuracy_score(ytest,ypred50)

In [369]:
acc500 = metrics.accuracy_score(ytest,ypred500)

In [370]:
acc5

0.7433371958285052

In [371]:
acc50

0.8102549246813442

In [372]:
acc500

0.8253186558516802

In [348]:
yy = fftest.target
yya = pp.fit_transform(yy)

In [349]:
yya

array([0, 0, 0, ..., 2, 2, 2])

In [350]:
fftestx = fftest.drop(['target'], axis=1)

In [351]:
fftestx

att1      att2      att3      att4      att5      att6      att7  \
0      0.002502 -0.000671 -0.000977  0.002106 -0.001190  0.000427  0.000397   
1      0.003174  0.001373 -0.000702  0.000336  0.000153  0.001190 -0.001678   
2     -0.002686 -0.001404  0.000061  0.000793 -0.000366 -0.000488 -0.001160   
3      0.002869  0.001892  0.002441  0.003052  0.004395  0.003174  0.003601   
4      0.000916  0.000214  0.000336  0.000824 -0.000763 -0.000275 -0.001465   
...         ...       ...       ...       ...       ...       ...       ...   
17254  0.000763 -0.001495 -0.003052 -0.004303 -0.008759 -0.013824 -0.015656   
17255  0.000793  0.000061  0.000153  0.001556 -0.001129 -0.000275  0.000214   
17256  0.008881  0.009094  0.006866  0.004730  0.003571  0.003723  0.001953   
17257 -0.006256 -0.004272 -0.000763 -0.000031 -0.000427 -0.002411 -0.002045   
17258  0.011200  0.009155  0.009247  0.011688  0.009583  0.008789  0.006622   

           att8      att9     att10  ...   att4991   att4992   att4993  \
0     -0.001129  0.001862  0.000671  ... -0.004883 -0.004517 -0.002899   
1      0.000885  0.002655 -0.000488  ...  0.000244  0.001923 -0.001831   
2     -0.000580 -0.000549 -0.001007  ... -0.000031 -0.000854 -0.001923   
3      0.003876  0.001984  0.002472  ...  0.002411  0.001923  0.003479   
4     -0.001312 -0.001373 -0.002167  ... -0.002106 -0.003143 -0.004639   
...         ...       ...       ...  ...       ...       ...       ...   
17254 -0.000061  0.016754  0.020966  ...  0.002014  0.004303  0.002197   
17255  0.000610  0.000732 -0.001953  ...  0.008026  0.007996  0.006500   
17256  0.001770  0.003876  0.004883  ...  0.002563  0.000519  0.000397   
17257 -0.007233 -0.004272 -0.004120  ...  0.017822  0.011047  0.012939   
17258  0.006653  0.008026  0.007751  ... -0.000763 -0.000061 -0.002014   

        att4994   att4995   att4996   att4997   att4998   att4999   att5000  
0     -0.002991 -0.001923 -0.003326 -0.004974 -0.006165 -0.005402 -0.005615  
1     -0.002441  0.002136  0.000397  0.000153  0.001526 -0.000488 -0.000854  
2     -0.001099 -0.002258  0.000244 -0.003235 -0.004486 -0.000092 -0.000122  
3      0.003357  0.003387  0.002869  0.003357  0.006287  0.003998  0.003693  
4     -0.006927 -0.004913  0.003204  0.022491  0.035614  0.033569  0.033356  
...         ...       ...       ...       ...       ...       ...       ...  
17254  0.002411  0.004120  0.002533  0.001343  0.002502  0.002167  0.001617  
17255  0.006317  0.008514  0.010193  0.007965  0.008575  0.009766  0.008057  
17256  0.000336  0.001343  0.002441  0.003204  0.001160  0.003052  0.003021  
17257  0.014832  0.011475  0.011597  0.008331  0.005310  0.005341  0.006897  
17258 -0.000244 -0.000366 -0.000275  0.000336 -0.001038 -0.000702 -0.000061  

[17259 rows x 5000 columns]

In [373]:
yypred5 = rfc5.predict(fftestx)

In [374]:
yypred50 = rfc50.predict(fftestx)

In [375]:
yypred500 = rfc500.predict(fftestx)

In [381]:
yypred5[1:50]

array([0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1])

In [380]:
yypred50[1:50]

array([0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1])

In [382]:
yypred500[1:50]

array([0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1])

In [384]:
aacc5 = metrics.accuracy_score(yya,yypred5)

In [385]:
aacc50 = metrics.accuracy_score(yya,yypred50)

In [386]:
aacc500 = metrics.accuracy_score(yya,yypred500)

In [387]:
aacc5

0.7483631728373602

In [388]:
aacc50

0.813952140911988

In [389]:
aacc500

0.8208470942696564